[package]
name = "battery-notify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = {version = "4.8.0"} 
battery = "0.7.8"
clap = { version = "4.2.4", features = ["derive"] }
